services:
  chat-backend:
    build:
      context: ./chat-backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_DB_PATH=/data/local.db
      - APP_DATA_PATH=/data
      - APP_ASSETS_PATH=/assets
    volumes:
      - ./data:/data
  chat-frontend:
    build:
      context: ./chat-frontend
      dockerfile: dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - chat-backend
  llama:
    build:
      context: ./llama-cpp
      dockerfile: ../dockerfile.llama
    ports:
      - "8080:8080"
    volumes:
      - ./models/gemma-3-12B-it-Q4.gguf:/llm-models/model.gguf
    environment:
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=8080
      - LLAMA_ARG_MODEL=/llm-models/model.gguf
      - LLAMA_ARG_NO_WEBUI=true
      - LLAMA_ARG_CONTEXT_SHIFT=true
      - LLAMA_ARG_CTX_SIZE=32768
      - LLAMA_ARG_JINJA=true
      - LLAMA_ARG_N_GPU_LAYERS=100
      - LLAMA_API_KEY=none
