FROM python:3.12-slim

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y poppler-utils
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/. /app/.
COPY ./assets /assets

WORKDIR /
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
